/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chris
 */
public class MHWGui extends javax.swing.JFrame {

    /**
     * Creates new form MHWGui
     */
    public MHWGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MHWRandom");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(515, 338));
        setSize(new java.awt.Dimension(400, 300));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Roll200.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setLabel("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 170, 110, 50);

        jScrollPane2.setBackground(new java.awt.Color(222, 222, 222));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setForeground(new java.awt.Color(1, 1, 1));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        resultText.setBackground(new java.awt.Color(1, 1, 1));
        resultText.setColumns(20);
        resultText.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        resultText.setForeground(new java.awt.Color(255, 255, 255));
        resultText.setRows(5);
        resultText.setWrapStyleWord(true);
        resultText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resultText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(resultText);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(44, 228, 400, 30);

        jLabel4.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Random Hunt");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 0, 260, 60);

        jLabel3.setFont(new java.awt.Font("Freestyle Script", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("* Random Weapon Type Roll");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 170, 20);

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("* Random Monster Roll");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 130, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Made By Kraftytek");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 280, 150, 19);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monsterhunterworld_sizeSM.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -70, 500, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Monster[] monster;

        monster = new Monster[59];

        monster[0] = new Monster("Rathian", "Dragon", 3);
        monster[1] = new Monster("Rathalos", "Dragon", 3);
        monster[2] = new Monster("Barroth", "Fire(Water when muddy)", 3);
        monster[3] = new Monster("Diablos", "Ice", 3);
        monster[4] = new Monster("Black Diablos", "Ice", 3);
        monster[5] = new Monster("Nergigante", "Thunder", 3);
        monster[6] = new Monster("Xeno'jiiva", "Fire, Water, Thunder, Ice, and Dragon", 2);
        monster[7] = new Monster("Pukei-Pukei", "Thunder", 3);
        monster[8] = new Monster("Kulve Taroth", "Thunder in Gold, Ice When Not", 3);
        monster[9] = new Monster("Pink Rathian", "Dragon", 3);
        monster[10] = new Monster("Azure Rathalos", "Dragon", 3);
        monster[11] = new Monster("Lavasioth", "Water", 2);
        monster[12] = new Monster("Dodogama", "Thunder", 3);
        monster[13] = new Monster("Kushala Daora", "Thunder/Dragon", 2);
        monster[14] = new Monster("Vaal Hazak", "Fire/Dragon", 3);
        monster[15] = new Monster("Legiana", "Thunder", 3);
        monster[16] = new Monster("Anjanath", "Water", 3);
        monster[17] = new Monster("Deviljho", "Thunder/Dragon", 2);
        monster[18] = new Monster("Great Jagras", "Fire", 3);
        monster[19] = new Monster("Zorah Magdaros", "Water/Dragon", 3);
        monster[20] = new Monster("Kirin", "Fire", 3);
        monster[21] = new Monster("Bazelgeuse", "Thunder", 3);
        monster[22] = new Monster("Paolumu", "Fire", 3);
        monster[23] = new Monster("Kulu-Ya-Ku", "Water", 3);
        monster[24] = new Monster("Jyuratodus", "Water in Mud, Thunder when not", 1);
        monster[25] = new Monster("Uragaan", "Water", 3);
        monster[26] = new Monster("Radobaan", "Dragon", 3);
        monster[27] = new Monster("Odogaron", "Ice", 3);
        monster[28] = new Monster("Great Girros", "Water", 3);
        monster[29] = new Monster("Lunastra", "Ice", 3);
        monster[30] = new Monster("Teostra", "Ice", 3);
        monster[31] = new Monster("Tobi-Kadachi", "Water", 3);
        monster[32] = new Monster("Tzitzi-Ya-Ku", "Thunder/Ice", 3);
        monster[33] = new Monster("Beotodus", "", 3);
        monster[34] = new Monster("Bandaro", "", 3);
        monster[35] = new Monster("Viper Tobi-Kadachi", "", 3);
        monster[36] = new Monster("Nightshade Palumu", "", 3);
        monster[37] = new Monster("Coral Pukei-Pukei", "", 3);
        monster[38] = new Monster("Barioth", "", 3);
        monster[39] = new Monster("Nargacuga", "", 3);
        monster[40] = new Monster("Glavenus", "", 3);
        monster[41] = new Monster("Tigrex", "", 3);
        monster[42] = new Monster("Brachydios", "", 3);
        monster[43] = new Monster("Shrieking Legiana", "", 3);
        monster[44] = new Monster("Fulgar Anjanath", "", 3);
        monster[45] = new Monster("Acidic Glavenus", "", 3);
        monster[46] = new Monster("Ebony Odogaron", "", 3);
        monster[47] = new Monster("Velkana", "", 3);
        monster[48] = new Monster("Seeting Bazelgeuse", "", 3);
        monster[49] = new Monster("Blackveil Vaal Hazak", "", 3);
        monster[50] = new Monster("Namielle", "", 3);
        monster[51] = new Monster("Savage Deviljho", "", 3);
        monster[52] = new Monster("Ruiner Nergigante", "", 3);
        monster[53] = new Monster("Shara Ishvalda", "", 3);
        monster[54] = new Monster("Zinogre", "", 3);
        monster[55] = new Monster("Stygian Zinogre", "", 3);
        monster[56] = new Monster("Yian Garuga", "", 3);
        monster[57] = new Monster("Scarred Yian Garuga", "", 3);
        monster[58] = new Monster("Rajang", "", 3);

        Weapons[] weapon;

        weapon = new Weapons[14];

        weapon[0] = new Weapons("Long Sword", "Slash");
        weapon[1] = new Weapons("Great Sword", "Slash");
        weapon[2] = new Weapons("Switch Axe", "Slash");
        weapon[3] = new Weapons("Dual Blades", "Slash");
        weapon[4] = new Weapons("Sword and Shield", "Slash");
        weapon[5] = new Weapons("Insect Glaive", "Slash");
        weapon[6] = new Weapons("Hammer", "Bludgeon");
        weapon[7] = new Weapons("Horn", "Bludgeon");
        weapon[8] = new Weapons("Light Bowgun", "Ranged");
        weapon[9] = new Weapons("Heavy Bowgun", "Ranged");
        weapon[10] = new Weapons("Bow", "Ranged");
        weapon[11] = new Weapons("Lance", "Peirce");
        weapon[12] = new Weapons("Gunlance", "Peirce");
        weapon[13] = new Weapons("Charge Blade", "Slash");

        int MonNum = RamNumb.RanNum(monster.length);
        int WepNum = RamNumb.RanNum(weapon.length);

        //boolean tempered = true;

        StringBuilder sb = new StringBuilder();

        sb.append("Ramez should hunt a ");
        sb.append(monster[MonNum].name);
        sb.append(" With a ");
        sb.append(weapon[WepNum].name);

        String text = sb.toString();

        resultText.setText(text);


    }//GEN-LAST:event_jButton1ActionPerformed
/*
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MHWGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MHWGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MHWGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MHWGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MHWGui().setVisible(true);
            }
        });
        */
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultText;
    // End of variables declaration//GEN-END:variables
}
